stages:
- stage: Build
  displayName: 'Build Stage'
  jobs:
  - job: Build
    displayName: 'Build the Function App'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '18.x'  # Use Node.js 18.x or your preferred version
      displayName: 'Install Node.js'

    - script: |
        npm install
      displayName: 'Install Dependencies'

    - script: |
        npm run build
      displayName: 'Build the Azure Function'

    - script: |
        zip -r functionapp.zip .
      displayName: 'Package Function App'

    - task: PublishBuildArtifacts@1
      inputs:
        pathToPublish: '$(System.DefaultWorkingDirectory)/functionapp.zip'
        artifactName: 'drop'
      displayName: 'Publish Artifacts'

- stage: Test
  displayName: 'Test Stage'
  dependsOn: Build
  jobs:
  - job: Test
    displayName: 'Run Unit Tests'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - script: |
        npm test
      displayName: 'Run Tests'

- stage: Deploy
  displayName: 'Deploy to Azure'
  dependsOn: Test
  condition: succeeded()
  jobs:
  - job: Deploy
    displayName: 'Deploy Function to Azure'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: DownloadBuildArtifacts@0
      inputs:
        artifactName: 'drop'
        downloadPath: '$(System.ArtifactsDirectory)'
      displayName: 'Download Build Artifacts'

    - task: AzureFunctionApp@1
      inputs:
        azureSubscription: 'MyAzureServiceConnection'  # Replace with your Azure service connection name
        appName: 'myAzureFunctionApp'             # Replace with your Azure Function App name
        package: '$(System.ArtifactsDirectory)/functionapp.zip'
      displayName: 'Deploy Function to Azure'
